## Softmax function

$$S(y_i) = \frac {e^{y_j}} {\sum_{j} e^{y_j}}$$


In [1]:
import tensorflow as tf
import numpy as np

In [2]:
xy = np.loadtxt('train_data/lab06_train.txt', unpack=True, dtype='float32')
x_data = np.transpose(xy[0:3])
y_data = np.transpose(xy[3:])

In [3]:
# tf Graph Input
X = tf.placeholder("float", [None, 3]) # x1, x2 and 1 (for bias)
Y = tf.placeholder("float", [None, 3]) # A, B, C => 3 classes
# Set modle weights
W = tf.Variable(tf.zeros([3, 3]))

### WX vs XW

x가 한개가 아니라 여러개가 되고 x의 값이 여러개가 되기 때문에 그것을 조금 더 쉽게 처리하기 위한 하나의 트릭.  
순서나 행과 열의 의미는 크지않다

In [4]:
# Construct model
# First, we multiply x by W with the expression tf.matmul(x, W).
# This is flipped from when we multiplied them in out equation,
# where we had Wx, as a small trick to deal with x being
# a 2D tensor with multiple inputs.
# We then add b, and finally apply tf.nn.softmax.
hypothesis = tf.nn.softmax(tf.matmul(X, W)) # Softmax

In [5]:
# Minimize error using cross entropy
learning_rate = 0.001

$D(S, L) = - \sum_i L_i log(S_i)$

In [6]:
# Corss entropy
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), reduction_indices=1))

In [7]:
#Gradient Descent
optimizer = tf.train.GradientDescentOptimizer(learning_rate).minimize(cost)

In [8]:
# Initializing the variables
init = tf.global_variables_initializer()

In [9]:
# Launch the graph
sess = tf.Session()
sess.run(init)

for step in range(2001):
    sess.run(optimizer, feed_dict={X:x_data, Y:y_data})
    if step % 200 == 0:
        print (step, sess.run(cost, feed_dict={X:x_data, Y:y_data}), sess.run(W))

0 1.09774 [[ -8.33333252e-05   4.16666626e-05   4.16666480e-05]
 [  1.66666694e-04   2.91666773e-04  -4.58333408e-04]
 [  1.66666636e-04   4.16666706e-04  -5.83333429e-04]]
200 1.05962 [[-0.02051384 -0.00103983  0.02155367]
 [ 0.01406438  0.01097753 -0.02504191]
 [ 0.01431208  0.03574873 -0.05006079]]
400 1.04985 [[-0.04282598 -0.00625899  0.04908497]
 [ 0.01747187  0.00156368 -0.01903554]
 [ 0.01831204  0.04954104 -0.06785304]]
600 1.0407 [[-0.06517859 -0.01176361  0.07694222]
 [ 0.01943521 -0.00848972 -0.01094548]
 [ 0.0211558   0.06118308 -0.0823388 ]]
800 1.03194 [[-0.08734013 -0.01729389  0.10463405]
 [ 0.0211172  -0.01796171 -0.00315548]
 [ 0.02396628  0.07198346 -0.09594974]]
1000 1.02354 [[-0.10928574 -0.02282181  0.13210757]
 [ 0.02266254 -0.02678034  0.00411783]
 [ 0.02685853  0.08210357 -0.10896212]]
1200 1.01547 [[-0.13101467 -0.02834092  0.15935561]
 [ 0.02409703 -0.03497621  0.01087923]
 [ 0.029832    0.091598   -0.12143001]]
1400 1.0077 [[-0.15252906 -0.03384715  0.18637

## Test & one-hot encoding

In [10]:
a = sess.run(hypothesis, feed_dict={X: [[1, 11, 7]]}) # bias, hours, attendance, A = [1, 0, 0]
print (a, sess.run(tf.arg_max(a, 1)))

b = sess.run(hypothesis, feed_dict={X:[[1, 3, 4]]})
print (b, sess.run(tf.arg_max(b, 1)))

c = sess.run(hypothesis, feed_dict={X:[[1, 1, 0]]})
print (b, sess.run(tf.arg_max(c, 1)))

[[ 0.46272627  0.35483006  0.18244371]] [0]
[[ 0.33820099  0.42101386  0.24078514]] [1]
[[ 0.33820099  0.42101386  0.24078514]] [2]


In [11]:
all = sess.run(hypothesis, feed_dict={X:[[1, 11, 7], [1, 3, 4], [1, 1, 0]]})
print (all, sess.run(tf.arg_max(all, 1)))

[[ 0.46272627  0.35483006  0.18244371]
 [ 0.33820099  0.42101386  0.24078514]
 [ 0.27002314  0.29085544  0.4391214 ]] [0 1 2]
