# Learning rate

In [1]:
import tensorflow as tf
import numpy as np

xy = np.loadtxt('train_data/lab06_train.txt', unpack=True, dtype='float32')
x_data = np.transpose(xy[0:3])
y_data = np.transpose(xy[3:])

# tf Graph Input
X = tf.placeholder("float", [None, 3]) # x1, x2 and 1 (for bias)
Y = tf.placeholder("float", [None, 3]) # A, B, C => 3 classes

# Set modle weights
W = tf.Variable(tf.zeros([3, 3]))

hypothesis = tf.nn.softmax(tf.matmul(X, W)) # Softmax

learning rate를 큰 값으로 준다.

In [2]:
# Minimize error using cross entropy
learning_rate = 10

In [3]:
# Corss entropy
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), reduction_indices=1))

#Gradient Descent
optimizer = tf.train.GradientDescentOptimizer(learning_rate).minimize(cost)

# Initializing the variables
init = tf.global_variables_initializer()

# Launch the graph
sess = tf.Session()
sess.run(init)

for step in range(2001):
    sess.run(optimizer, feed_dict={X:x_data, Y:y_data})
    if step % 200 == 0:
        print (step, sess.run(cost, feed_dict={X:x_data, Y:y_data}), sess.run(W))

0 nan [[-0.83333319  0.4166666   0.41666645]
 [ 1.66666687  2.91666746 -4.58333397]
 [ 1.66666627  4.16666698 -5.83333397]]
200 nan [[ nan  nan  nan]
 [ nan  nan  nan]
 [ nan  nan  nan]]
400 nan [[ nan  nan  nan]
 [ nan  nan  nan]
 [ nan  nan  nan]]
600 nan [[ nan  nan  nan]
 [ nan  nan  nan]
 [ nan  nan  nan]]
800 nan [[ nan  nan  nan]
 [ nan  nan  nan]
 [ nan  nan  nan]]
1000 nan [[ nan  nan  nan]
 [ nan  nan  nan]
 [ nan  nan  nan]]
1200 nan [[ nan  nan  nan]
 [ nan  nan  nan]
 [ nan  nan  nan]]
1400 nan [[ nan  nan  nan]
 [ nan  nan  nan]
 [ nan  nan  nan]]
1600 nan [[ nan  nan  nan]
 [ nan  nan  nan]
 [ nan  nan  nan]]
1800 nan [[ nan  nan  nan]
 [ nan  nan  nan]
 [ nan  nan  nan]]
2000 nan [[ nan  nan  nan]
 [ nan  nan  nan]
 [ nan  nan  nan]]


learning rate이 너무 커서 overshooting이 되어서 학습이 전혀 일어나지 않않다

learning rate를 작은 값으로 주었다.

In [4]:
# Minimize error using cross entropy
learning_rate = 0.0001

In [5]:
# Corss entropy
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), reduction_indices=1))

#Gradient Descent
optimizer = tf.train.GradientDescentOptimizer(learning_rate).minimize(cost)

# Initializing the variables
init = tf.global_variables_initializer()

# Launch the graph
sess = tf.Session()
sess.run(init)

for step in range(2001):
    sess.run(optimizer, feed_dict={X:x_data, Y:y_data})
    if step % 200 == 0:
        print (step, sess.run(cost, feed_dict={X:x_data, Y:y_data}), sess.run(W))

0 1.09774 [[ -8.33333252e-05   4.16666626e-05   4.16666480e-05]
 [  1.66666694e-04   2.91666773e-04  -4.58333408e-04]
 [  1.66666636e-04   4.16666706e-04  -5.83333429e-04]]
200 1.05962 [[-0.02051384 -0.00103983  0.02155367]
 [ 0.01406438  0.01097753 -0.02504191]
 [ 0.01431208  0.03574873 -0.05006079]]
400 1.04985 [[-0.04282598 -0.00625899  0.04908497]
 [ 0.01747187  0.00156368 -0.01903554]
 [ 0.01831204  0.04954104 -0.06785304]]
600 1.0407 [[-0.06517859 -0.01176361  0.07694222]
 [ 0.01943521 -0.00848972 -0.01094548]
 [ 0.0211558   0.06118308 -0.0823388 ]]
800 1.03194 [[-0.08734013 -0.01729389  0.10463405]
 [ 0.0211172  -0.01796171 -0.00315548]
 [ 0.02396628  0.07198346 -0.09594974]]
1000 1.02354 [[-0.10928574 -0.02282181  0.13210757]
 [ 0.02266254 -0.02678034  0.00411783]
 [ 0.02685853  0.08210357 -0.10896212]]
1200 1.01547 [[-0.13101467 -0.02834092  0.15935561]
 [ 0.02409703 -0.03497621  0.01087923]
 [ 0.029832    0.091598   -0.12143001]]
1400 1.0077 [[-0.15252906 -0.03384715  0.18637

learning rate를 너무 작은 값으로 주어서 학습이 거의 일어나지 않았다

In [6]:
# Minimize error using cross entropy
learning_rate = 0.1

In [7]:
# Corss entropy
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), reduction_indices=1))

#Gradient Descent
optimizer = tf.train.GradientDescentOptimizer(learning_rate).minimize(cost)

# Initializing the variables
init = tf.global_variables_initializer()

# Launch the graph
sess = tf.Session()
sess.run(init)

for step in range(2001):
    sess.run(optimizer, feed_dict={X:x_data, Y:y_data})
    if step % 200 == 0:
        print (step, sess.run(cost, feed_dict={X:x_data, Y:y_data}), sess.run(W))

0 1.0678 [[-0.00833333  0.00416667  0.00416666]
 [ 0.01666667  0.02916667 -0.04583334]
 [ 0.01666666  0.04166667 -0.05833334]]
200 0.699681 [[-1.5737735  -0.36410642  1.93788099]
 [ 0.0967759  -0.09235884 -0.00441682]
 [ 0.24915566  0.23823613 -0.48739177]]
400 0.594579 [[-2.54309034 -0.43173078  2.97482228]
 [ 0.13064831 -0.04841127 -0.08223619]
 [ 0.40734777  0.22857714 -0.63592446]]
600 0.535829 [[-3.31521416 -0.39115471  3.70637012]
 [ 0.13982886 -0.02464214 -0.11518568]
 [ 0.54843497  0.21297167 -0.76140594]]
800 0.494312 [[-3.98393679 -0.31143472  4.29537106]
 [ 0.1417881  -0.00935038 -0.13243635]
 [ 0.6748786   0.1950776  -0.86995488]]
1000 0.461916 [[ -4.58334923e+00  -2.18527570e-01   4.80187750e+00]
 [  1.41456679e-01   1.54198625e-03  -1.42996773e-01]
 [  7.89354861e-01   1.77009344e-01  -9.66362596e-01]]
1200 0.435343 [[-5.13021469 -0.12343737  5.25365353]
 [ 0.14044461  0.00979479 -0.15023731]
 [ 0.89399701  0.15975396 -1.05374885]]
1400 0.412891 [[-5.63466215 -0.03106253 

어느정도 학습이 되었다.

## MNIST Dataset